SELECT T3.CURRENCYCODE, 
CAST(SUM(LINEAMOUNT) AS MONEY) AS Online_GrossDemandCashValue_Today,
COUNT(DISTINCT T2.SALESID) AS Online_Orders_Today, COUNT(T2.SALESID) AS Online_OrderLines_Today
  FROM AXDB_PROD.dbo.KRFSALESTABLEEXTENDED AS T1, AXDB_PROD.dbo.SALESTABLE AS T2, AXDB_PROD.dbo.SALESLINE AS T3
  WHERE T1.SALESTABLE = T2.RECID AND T2.SALESID = T3.SALESID AND T2.DATAAREAID = T3.DATAAREAID AND CONVERT(DATE, T1.CREATEDDATETIME) = CONVERT(DATE, getUTCdate()) AND SALESORDERCATEGORY = 'ONLINE' AND T3.SALESTYPE = 3
  GROUP BY T3.CURRENCYCODE
