SELECT CONCAT(SALESORDERCATEGORY, ' ', UPPER(DATAAREAID)) AS SALESORDERCATEGORY, COUNT(*) AS OrdersPerHour
  FROM AXDB_PROD.dbo.KRFSALESTABLEEXTENDED
  WHERE CREATEDDATETIME > DATEADD(HOUR, -1, getUTCdate()) AND SALESORDERCATEGORY = 'ONLINE'
  GROUP BY SALESORDERCATEGORY, DATAAREAID
