SELECT CONCAT('ONLINE ', UPPER(T1.DATAAREAID)) AS SALESORDERCATEGORY, COUNT(*) AS OrdersInvoicedPerHour
  FROM AXDB_PROD.dbo.CUSTINVOICEJOUR AS T1
  WHERE T1.CREATEDDATETIME > DATEADD(HOUR, -1, getUTCdate()) AND CUSTGROUP = 'R-eComm' AND T1.SALESTYPE = 3 
  GROUP BY T1.DATAAREAID
