SELECT CONCAT(T1.SALESORDERCATEGORY, ' ', UPPER(T1.COMPANYID)) AS SALESORDERCATEGORY, COUNT(DISTINCT T1.HOSTORDERID) AS OrdersSentToXPOPerHour, COUNT(*) AS LinesSentToPerHour
  FROM AXDB_PROD.dbo.DMFTEDECOMSHIPMENTINFOENTITY AS T1
  WHERE T1.CREATEDDATETIME > DATEADD(HOUR, -1, getUTCdate()) AND T1.DEFINITIONGROUP LIKE '\[XPO\] \[IDD03D\]%' ESCAPE '\'
  GROUP BY T1.SALESORDERCATEGORY, T1.COMPANYID
